// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/documentapi/document.proto

/*
Package documentapi is a generated protocol buffer package.

It is generated from these files:
	pkg/documentapi/document.proto

It has these top-level messages:
*/
package documentapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Document service

type DocumentClient interface {
}

type documentClient struct {
	cc *grpc.ClientConn
}

func NewDocumentClient(cc *grpc.ClientConn) DocumentClient {
	return &documentClient{cc}
}

// Server API for Document service

type DocumentServer interface {
}

func RegisterDocumentServer(s *grpc.Server, srv DocumentServer) {
	s.RegisterService(&_Document_serviceDesc, srv)
}

var _Document_serviceDesc = grpc.ServiceDesc{
	ServiceName: "documentapi.Document",
	HandlerType: (*DocumentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "pkg/documentapi/document.proto",
}

func init() { proto.RegisterFile("pkg/documentapi/document.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 64 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0xc8, 0x4e, 0xd7,
	0x4f, 0xc9, 0x4f, 0x2e, 0xcd, 0x4d, 0xcd, 0x2b, 0x49, 0x2c, 0xc8, 0x84, 0xb3, 0xf5, 0x0a, 0x8a,
	0xf2, 0x4b, 0xf2, 0x85, 0xb8, 0x91, 0xe4, 0x8c, 0xb8, 0xb8, 0x38, 0x5c, 0xa0, 0xdc, 0x24, 0x36,
	0xb0, 0xbc, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x14, 0xc8, 0xd4, 0x41, 0x00, 0x00, 0x00,
}
